### ISSUE TITLE
deploy to maven central

### ISSUE THREAD

**Issue by domdorn** [playframework/play-joda#5]
Just came up on gitter: Apparently play-joda is not deployed to maven-central, thus making it hard for people to upgrade to the 2.6 snapshots/milestones

**Comment by gmethvin** [comment]
So we actually want to split into two different libraries before we deploy:
 - play-json-joda: only depends on play-json
 - play-joda: depends on play, support for play forms.

I was actually thinking we might want to move the play-json-joda to the play-json repository, since it seems like it'd make sense to manage it there.

**Comment by domdorn** [comment]
hmm... how about we rename play-joda to play-forms-joda ?

**Comment by gmethvin** [comment]
I don't have a strong opinion either way. The point is that play-joda depends on the "play" library and play-json-joda only depends on play-json.

**Comment by domdorn** [comment]
hmm.. at the moment, the only stuff in here are bindings for the forms... are there plans to ever pull the form processing into a own module, e.g. play-forms ?

**Comment by gmethvin** [comment]
FYI, I created a play-joda-forms in playframework (this will be released along with play), and we already have a play-json-joda in the play-json repo.

I'll remove this repo to avoid any confusion.

/cc @schmitch
